### ISSUE TITLE
Deposit tx confirmed but getbalance still 0

### ISSUE THREAD

**Issue by reliveyy** [BoltzExchange/boltz-lnd#22] opened 2020-09-01 22:00 UTC
I'm using a fresh xud-docker mainnet. I tried to `deposit btc`. The deposit transaction is confirmed (https://www.blockchain.com/btc/address/37L1Dhudf2oj6iR23t4NHbTBHKpMZ2KmzA) but `getbalance` comamnd still shows btc balance 0.

```
LND-BTC Info:
┌──────────┬──────────────────────────────────────────────────────────────────────┐
│ Status   │ Ready                                                                │
├──────────┼──────────────────────────────────────────────────────────────────────┤
│ Version  │ 0.11.0-beta commit=v0.11.0-beta                                      │
├──────────┼──────────────────────────────────────────────────────────────────────┤
│ Address  │ 02e8f7767858ca443a70e186685b15ad438f75f081efe9f2a30bc45993bcb88722   │
│          │ @dseqdyqjht4bmggv7ifbzbtviavjawevwqkyclfgpfg2zl57jv5gwhad.onion:9735 │
├──────────┼──────────────────────────────────────────────────────────────────────┤
│ Alias    │ 02e8f7767858ca443a70                                                 │
├──────────┼──────────────────────────────────────────────────────────────────────┤
│ Channels │ Active: 1 | Pending: 0 | Closed: 0                                   │
├──────────┼──────────────────────────────────────────────────────────────────────┤
│ Network  │ bitcoin mainnet                                                      │
└──────────┴──────────────────────────────────────────────────────────────────────┘
```

```
General XUD Info
┌───────────────┬──────────────────────────────────────────────────────────────────────┐
│ Status        │ LND-LTC: lnd-LTC has no active channels                              │
├───────────────┼──────────────────────────────────────────────────────────────────────┤
│ Alias         │ IdentifyBusy                                                         │
├───────────────┼──────────────────────────────────────────────────────────────────────┤
│ Node Key      │ 033b647b3bb44aa607948c4d026456191db5e0c63ef7777d2cf863c08613a3ac8c   │
├───────────────┼──────────────────────────────────────────────────────────────────────┤
│ Address       │ 033b647b3bb44aa607948c4d026456191db5e0c63ef7777d2cf863c08613a3ac8c   │
│               │ @r4fotfhcvkwdyco76jaolm4b6wcp7dhbjci5ivghy3nkwwh473u6q4ad.onion:8885 │
├───────────────┼──────────────────────────────────────────────────────────────────────┤
│ Network       │ mainnet                                                              │
├───────────────┼──────────────────────────────────────────────────────────────────────┤
│ Version       │ 1.0.0-beta.8-aa3027a6                                                │
├───────────────┼──────────────────────────────────────────────────────────────────────┤
│ Peers         │ 4                                                                    │
├───────────────┼──────────────────────────────────────────────────────────────────────┤
│ Pairs         │ 4                                                                    │
├───────────────┼──────────────────────────────────────────────────────────────────────┤
│ Own orders    │ 0                                                                    │
├───────────────┼──────────────────────────────────────────────────────────────────────┤
│ Peer orders   │ 4                                                                    │
├───────────────┼──────────────────────────────────────────────────────────────────────┤
│ Pending swaps │ []                                                                   │
└───────────────┴──────────────────────────────────────────────────────────────────────┘
```

**Comment by peartobear** [comment] 2020-09-02 14:30
Boltz Logs

```
Sep 02 09:43:24 mainnet boltzd[2067]: 9/2/2020, 09:43:24 verbose: Claiming BTC Swap 70YJ1m output: dc5b85bcb8d435d88c83ceb49eb891fb4f548c064bd696b528954776f1cdaa4c:1
Sep 02 09:43:24 mainnet boltzd[2067]: 9/2/2020, 09:43:24 debug: Could not pay invoice of Swap 70YJ1m: insufficient_balance
```

Looks like the min amount doesn't work for swap and we should push it higher in boltz backend

**Comment by michael1011** [comment] 2020-09-07 20:49
This issue is caused by really small channel creation swaps because the boltz backend doesn't take the commit fee of the channel into account when opening one. Will be fixed by bumping the mainnet minimal limits

**Closed by michael1011** 2020-09-07 20:49 UTC
Labels: P1
